version: '3.8'

services:
  plesk:
    image: plesk/plesk
    ports:
      - "8080:80"
      - "443:443"
      - "8880:8880"
      - "8443:8443"
      - "8447:8447"
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
