version: '3.9'
services:
  php-server:
    image: php:apache
    ports:
      - "8082:80"
    volumes:
      - ./html:/var/www/html
    restart: always

  db:
      image: linuxserver/mariadb:latest
      restart: always
      environment:
        MYSQL_DATABASE: database
        MYSQL_USER: user
        MYSQL_PASSWORD: password
        MYSQL_ROOT_PASSWORD: password
      volumes:
        - ./db:/config/databases

volumes:
  php-server:
  db:
