services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ispconfig
      MYSQL_USER: ispconfig
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

  web:
    image: lspg/ispconfig
    restart: always
    environment:
      ISP_CONFIG_CLIENT_PORT: 8080
      ISP_CONFIG_CLIENT_TLS_PORT: 8443
      ISP_CONFIG_MYSQL_HOST: db
      ISP_CONFIG_MYSQL_ROOT_USER: root
      ISP_CONFIG_MYSQL_ROOT_PASSWORD: password
      ISP_CONFIG_MYSQL_DATABASE: ispconfig
      ISP_CONFIG_MYSQL_USER: ispconfig
      ISP_CONFIG_MYSQL_PASSWORD: password
    ports:
      - "8080:8080"
      - "8443:8443"
    depends_on:
      - db
    volumes:
      - web_config:/usr/local/ispconfig
      - web_data:/var/www

volumes:
  db_data:
  web_config:
  web_data:
