version: '3.7'

services:
    phoneinfoga:
      container_name: phoneinfoga
      restart: always
      image: sundowndev/phoneinfoga:latest
      command:
        - "serve"
      ports:
        - "80:5000"
